### ISSUE TITLE
nix-env -qa and nix search don't work

### ISSUE THREAD

**Issue by jjakob** [t184256/nix-on-droid-bootstrap#27]
This is a fresh install from f-droid version 0.66_v0.2.2_nix, Android 7.1.2 LineageOS 14.1. The bootstrap installed fine.
For example `nix-env -qa dnsutils` returns `error: selector 'dnsutils' matches no derivations`
`nix search dnsutils` returns `error: executing '': No such file or directory`

Trying to open /data/data/com.termux.nix/files/usr/usr/lib/login-inner with a file manager returns a file not found error (tried with Amaze internal text editor and Quickedit).

**Comment by t184256** [comment]
> `nix-env -qa dnsutils` returns `error: selector 'dnsutils' matches no derivations`

And what's the intended result? I don't know what it should do, and my Fedora+Nix box prints the same thing.

> `nix search dnsutils` returns `error: executing '': No such file or directory`

Can reproduce, sounds like a bug.

> Trying to open `/data/data/com.termux.nix/files/usr/usr/lib/login-inner` with a file manager returns a file not found error

You're well past that point and this script did its job just fine, but thanks for bringing the attention to the fact that this path is now only accessible from within the app itself. The instructions should be updated.

**Comment by t184256** [comment]
A-ha! It's just a broken $PAGER in minimal install, see https://github.com/NixOS/nix/issues/706 and all the solutions from there.

**Comment by jjakob** [comment]
Thanks, export PAGER=cat or installing less (automatically sets PAGER to less) both work.
