### ISSUE TITLE
home manager wont install on any device

### ISSUE THREAD

**Issue by puddingepoch** [t184256/nix-on-droid-bootstrap#33]
i can't get home manager to install on any devices, i have tried it on 6 devices so far 

hauwei mate SE
google pixel 
samsung tab S
samsung s6, s7 
hauwei media pad
samsung note 4 

its all the same error, i will attach an image because select all doesn't work on this lovely little app and it files i write in nix-on-droid are for some reason impossible to find on android (thanks for that) 

I've attached images of it

![Screenshot_20200101-213604_Nix (1)](https://user-images.githubusercontent.com/59093378/71649970-01f02300-2ce1-11ea-9b30-e3f940d08101.jpg)
![Screenshot_20200101-211922](https://user-images.githubusercontent.com/59093378/71649974-074d6d80-2ce1-11ea-9e49-44fd0bf49860.png)

There will be no further complaints from me here, this is broken garbage and i wish you the best of luck fixing it 

uninstalled thanks

**Comment by t184256** [comment]
Whatever. Work on your tone, read the error messages next time, and good luck.
