### ISSUE TITLE
Style settings can not be applied

### ISSUE THREAD

**Issue by ln-nl** [t184256/nix-on-droid-bootstrap#4]
### Steps to reproduce

- Install app-debug.apk
- Style -> Choose Color -> Select any color
Popup appears:
```
Failed to install file:

Application package com.termux not found
```
- Install termux from Google Play (should I?)
- Style -> Choose Color -> Select any color
Popup appears:
```
Failed to install file:

Cannot create termux dir=/data/user/0/com.termux/files/home/.termux
```

**Comment by t184256** [comment]
Actually should be filed against https://github.com/t184256/nix-on-droid-app.

> Install termux from Google Play (should I?)

No.

I don't have my device at hand, but I have a fairly good idea where it fails, so you can try a 'blind fix' at the moment. May fail on some subsequent stuff though.
https://nix-on-droid.unboiled.info/apk-debug-blind-styling-fix.apk

**Comment by ln-nl** [comment]
It works, thank you!
