### ISSUE TITLE
Relicense under MIT?

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid-bootstrap#44]
@Gerschtli 

Let's branch off the discussion here.

Las year, [in a different repo](https://github.com/t184256/nix-in-termux) altogether, I've started to bring Nix to Android. Back in the days, it was a Nix installation script heavily inspired by the official one, which I presumed to be authored by @edolstra and published under LGPL 2.1. Or at least I hope so, because it doesn't really come with a license header.

I thought that one day it could ship as part of a Nix, as a script to install it under Termux, so I kept the license. 

Then I rewrote everything, going self-contained and Termux-free, installing through zipballs instead, but kept the license. Then you rewrote it, and kept the license.

If I were asked to trace it back to the original Nix script, I'd say that only these these two lines are what's lifted from the original install script and made it through the rewrites:

    USER=${config.user.userName} ${prootCommand} "$PKG_NIX/bin/nix-store" --init
    USER=${config.user.userName} ${prootCommand} "$PKG_NIX/bin/nix-store" --load-db < .reginfo

What we're heading towards today, for better or worse, is home-manager, nixos or nix-darwin territory. I would argue that this is small enough to be uncopyrightable, and those three projects already bear more similarity to nix-on-droid.

That said, how do you feel about relicensing the whole contents of this repo to MIT?

**Comment by Gerschtli** [comment]
I am completely okay with relicensing it. As I said before, I am not that into the license thing: What are the consequences of this step. Will it simplify the reuse/modification of home-manager, nixos or nix-darwin code?

**Comment by t184256** [comment]
> As I said before, I am not that into the license thing

Heh, it doesn't work that way, really =) It's like saying "I'm not into this law thing" - the laws, lawmakers and law enforcement don't really care about your opinions, you're subject to that no matter what. But yeah, it's a quite a hindrance at times.

> Will it simplify the reuse/modification of home-manager, nixos or nix-darwin code?

Yes, we won't have to do neither mixed licensing nor that 'permissive with GPL modifications tainting it' thing, we'll only need to preserve the author names, basically. But more importantly, those would be able to reuse our changes back, which would be a nightmare in any other scenario.

If you agree, we need to replace the license text and update the license headers, and then land your latest PRs. I can do it myself, but I'm just about to start my workday, so it'll have to wait for quite some time.

**Comment by Gerschtli** [comment]
> Heh, it doesn't work that way, really =)

Yeah.. I know, I should have a deeper look into that. :D

> If you agree, we need to replace the license text and update the license headers, and then land your latest PRs. I can do it myself, but I'm just about to start my workday, so it'll have to wait for quite some time.

Sounds like a plan ;)

**Comment by t184256** [comment]
I think I've found an acceptable balance between brevity and compliance (and it's definitely more than the others are doing).

Please rebase your PRs to ad73458 (sorry for a force-push, I've added the header to the config template again).

When using MIT-licensed code from other projects, add notices in the following format:

```
# Copyright (c) 2019-2020, see AUTHORS. Licensed under MIT License, see LICENSE.

# <Inspired by|Based off|Uses XYZ from|...>
# <url-of-the-file>
# (<original copyright notice taken from LICENSE of the project you're borrowing from>,
#  licensed under MIT License as well)
```

See example in modules/environment/etc/make-etc.sh.

For other files, just the first line should suffice.

**Comment by Gerschtli** [comment]
That sounds good, but maybe you should remove this header from the nix-on-droid.nix.default :)
Will rebase my PRs tomorrow

**Comment by t184256** [comment]
Yes, definitely, see above.

**Comment by Gerschtli** [comment]
Ah, sorry, my bad ;)
