### ISSUE TITLE
Building proot is not automated

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid-bootstrap#6]
Unfortunately my attempts for naively cross-compiling static-linked proot as `pkgsCross.armv7a-android-prebuilt.pkgsStatic.proot` or `pkgsCross.aarch64-multiplatform.pkgsStatic.proot` failed: the produced binaries crashed with the dreaded bus error that I don't know how to debug, so I resorted to building proot manually for now.

This may be a desperate shot in the dark, but when I type 'cross-compiling static-linked... with nix`, there's a name that rings inside my head and this name is @matthewbauer. Matthew, if you have a minute, do you have any insights on why could that produce a binary that crashes with 'Bus error'? Have you tried combining crossSystem and pkgsStatic?

**Comment by ln-nl** [comment]
(it may be useful: https://github.com/NixOS/nixpkgs/pull/58504/commits/52566c3b7b5f96d198dd6e57e2db37012fd9b71b)

**Comment by t184256** [comment]
Mindlessly tried building

    pkgsCross.aarch64-multiplatform.pkgsStatic.proot
    .overrideAttrs (oa: {
      version = "2019-03-12";
      src = pkgs.fetchFromGitHub {
        repo = "proot";
        owner = "termux";
        rev = "09568e21ff9fee7a6907be34a2d0fde3bacca7eb";
        sha256 = "1091si4i07349y7x7sx1r904gg3c9a3m39xkv24fakjlirpi3lpy";
      };
      makeFlags = [ "-Csrc CFLAGS=-D__ANDROID__" ];
    }))
    .override {
      enablePython = false;
    )

from that checkout, got a `proot` that dies with a Bus Error on a very early `mkdir`.

**Comment by matthewbauer** [comment]
Hmm... it's possible that the proot fork only works with bionic? That gets trickier because we don't have a good way to cross execute android linker. Something like this should work:

```
let
  pkgs = import <nixpkgs> {
    crossSystem = (import <nixpkgs/lib>).systems.examples.aarch64-multiplatform-musl;
    crossOverlays = [ (import <nixpkgs/pkgs/top-level/static.nix>) ];
  };
  proot = pkgs.proot.override { enablePython = false; };
in pkgs.runCommand "test" {} ''
  ${pkgs.stdenv.hostPlatform.emulator pkgs.buildPackages} ${proot}/bin/proot --version
''
```

but there's obviously some things specific to android that could be causing the bus error.

**Comment by t184256** [comment]
Interesting, maybe I do need bionic.

Did I understand your suggestion correctly: build `proot` statically, but use `aarch64-android-prebuilt` (and not `aarch64-multiplatform-musl` like in your example) to get it statically linked against bionic?

**Comment by matthewbauer** [comment]
Yeah, Musl *should* work with Android fine after all it is just linux. But it's definitely possible something is causing an issue.

**Comment by t184256** [comment]
Oh god, I pulled it off! I've cross-compiled a proot that works!

Everybody with even a bit of Nix knowledge is welcome to my [proot.nix](https://github.com/t184256/nix-on-droid-bootstrap/blob/master/proot.nix) to fix my sloppy cross-compiling (seriously, I've cut a lot of corners on that way, like, all of them).

Everybody with aarch64 devices is kindly asked to reinstall (or substitute proot) and go for another hunt for the dreaded bus error.
