### ISSUE TITLE
fails to build ghc

### ISSUE THREAD

**Issue by chenyulue** [t184256/nix-on-droid-bootstrap#8]
I use `nix-env -i ghc` to install GHC. However, when compiling `Distribution.SPDX.LIcenseId`, I get the following error:

> [123 of 270] Compiling Distribution.SPDX.LicenseId ( libraries/Cabal/Cabal/Distribution/SPDX/LicenseId.hs, bootstrapping/Distribution/SPDX/LicenseId.o )
> utils/genprimopcode/ghc.mk:19: utils/genprimopcode/dist/package-data.mk: No such file or directory
> make[1]: *** [utils/ghc-cabal/ghc.mk:56: utils/ghc-cabal/dist/build/tmp/ghc-cabal] Killed
> make: *** [Makefile:123: all] Error 2
> **error** (ignored): getting status of '/data/data/com.termux.nix/files/usr/tmp/nix-build-ghc-8.6.4.drv-1/ghc-8.6.4/utils/unlit/fs.c': Operation not permitted
> **error**: cannot unlink '/data/data/com.termux.nix/files/usr/tmp/nix-build-ghc-8.6.4.drv-1/ghc-8.6.4/utils/fs': Directory not empty

I have no idea why this happens and whether it is related to Nix-on-droid or just to GHC. 

Could you take some time to look into it when you are free? Thanks!

My android version is 7.1.1

**Comment by t184256** [comment]
Attempted to look into that, but hit an out-of-space error. Just wanted you to know that I'm on it, but it'll take some time.

**Comment by t184256** [comment]
Can reproduce under nix-on-droid.

**Comment by t184256** [comment]
By the way, how do you prevent long builds in nix-on-droid from being killed? =)

Building ghc times out even on Hydra (10h) and Hydra got some powerful hardware.

**Comment by bbigras** [comment]
Can we use nix-on-droid on the android emulator? I tried and the app crashed (or maybe just exited with an error).

**Comment by t184256** [comment]
I foresee no problems with that approach as long as either:

1) the emulator emulates aarch64

or

2) you teach me how to run it in the emulator and I'll add support for the required architectures.

**Comment by chenyulue** [comment]
@t184256 I re-install the app, and building ghc succeeds. 

BTW, on my phone (Meizu Pro 6s) building ghc took about 30 minutes, not as long as 10h. So I don't know your problem that long building is killed. But sometimes flyme os (customized Android by Meizu) can kill nix-on-droid when the screen is locked. So I permit nix-on-droid to run in the background and keep the screen unlocked while building ghc. This may help.

**Comment by chenyulue** [comment]
But again, building cabal-install fails. When compiling the 49th module, the process is killed. I don't know why.

**Comment by t184256** [comment]
> I re-install the app, and building ghc succeeds.

I reinstalled the app and ghc just installed without any compilation. O_o

Hydra shows [nixos:release-19.03-aarch64 builds](https://hydra.nixos.org/job/nixos/release-19.03-aarch64/nixpkgs.ghc.aarch64-linux) now.

Hooray?

**Comment by puffnfresh** [comment]
Yeah I had no problem with GHC. Should close this.
